language: php
php:
  - 5.4
  - 5.5
# Remove hhvm until https://github.com/facebook/hhvm/issues/1334 is fixed
#  - hhvm
before_script:
  - composer self-update
  - composer install --dev
script: bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml
after_script: bin/coveralls

notifications:
  email:
    - travis@b-zik.de
