language: php
php:
  - 5.4
  - 5.5
  - hhvm
before_script:
  - composer self-update
  - composer install --dev
script: phpunit --coverage-text --coverage-clover build/logs/clover.xml
after_script: bin/coveralls

notifications:
  email:
    - travis@b-zik.de
